import person1 from './images/person1.svg';
import person2 from './images/person2.svg';
import person3 from './images/person3.svg';
import person4 from './images/person4.svg';
import person5 from './images/person5.svg';
import person6 from './images/person6.svg';
import person7 from './images/person7.svg';

const teachers = [

    {
      id: 1,
      name: "John Doe",
      profession: "Software Engineer",
      hobbies: "Reading, Traveling, Photography",
      codeLanguages: "JavaScript, Python, Java",
      lifePhilosophy: "Live and let live.",
      email: "john.doe@example.com",
      phone: "+1234567890",
      city: "Tel Aviv",
      country: "Israel",
      img: person1
    },
    {
      id: 2,
      name: "Jane Smith",
      profession: "Data Scientist",
      hobbies: "Cooking, Hiking, Painting",
      codeLanguages: "R, SQL, Python",
      lifePhilosophy: "Strive for progress, not perfection.",
      email: "jane.smith@example.com",
      phone: "+9876543210",
      city: "Jerusalem",
      country: "Israel"
    },
    {
      id: 3,
      name: "Alex Johnson",
      profession: "UX Designer",
      hobbies: "Gardening, Playing Guitar, Cycling",
      codeLanguages: "HTML, CSS",
      lifePhilosophy: "Embrace the journey.",
      email: "alex.johnson@example.com",
      phone: "+5551234567",
      city: "Haifa",
      country: "Israel"
    },
    {
      id: 4,
      name: "Emily Brown",
      profession: "Product Manager",
      hobbies: "Sculpting, Running, Traveling",
      codeLanguages: "None",
      lifePhilosophy: "Learn from yesterday, live for today, hope for tomorrow.",
      email: "emily.brown@example.com",
      phone: "+1112223333",
      city: "Beer Sheva",
      country: "Israel"
    },
    {
      id: 5,
      name: "Michael Davis",
      profession: "DevOps Engineer",
      hobbies: "Fishing, Cooking, Gaming",
      codeLanguages: "Bash, Python",
      lifePhilosophy: "Adapt and overcome.",
      email: "michael.davis@example.com",
      phone: "+4445556666",
      city: "Ramat Gan",
      country: "Israel"
    },
    {
      id: 6,
      name: "Sophie Turner",
      profession: "Graphic Designer",
      hobbies: "Reading Comics, Sketching, Yoga",
      codeLanguages: "None",
      lifePhilosophy: "Create to express, not to impress.",
      email: "sophie.turner@example.com",
      phone: "+9998887777",
      city: "Netanya",
      country: "Israel"
    },
    {
      id: 7,
      name: "David Lee",
      profession: "Database Administrator",
      hobbies: "Chess, Gardening, Cooking",
      codeLanguages: "SQL",
      lifePhilosophy: "Knowledge is power.",
      email: "david.lee@example.com",
      phone: "+3332221111",
      city: "Ashdod",
      country: "Israel"
    },
    {
      id: 8,
      name: "Olivia White",
      profession: "Mobile App Developer",
      hobbies: "Photography, Running, Traveling",
      codeLanguages: "Swift, Kotlin",
      lifePhilosophy: "Dream big, work hard.",
      email: "olivia.white@example.com",
      phone: "+7776665555",
      city: "Petah Tikva",
      country: "Israel"
    },
    {
      id: 9,
      name: "Daniel Kim",
      profession: "Network Engineer",
      hobbies: "Cycling, Playing Piano, Watching Movies",
      codeLanguages: "Python, C++",
      lifePhilosophy: "Find joy in the journey.",
      email: "daniel.kim@example.com",
      phone: "+1112223333",
      city: "Holon",
      country: "Israel"
    },
    {
      id: 10,
      name: "Grace Miller",
      profession: "Frontend Developer",
      hobbies: "Painting, Hiking, Coding",
      codeLanguages: "JavaScript, HTML, CSS",
      lifePhilosophy: "Every day is a new beginning.",
      email: "grace.miller@example.com",
      phone: "+4445556666",
      city: "Herzlia",
      country: "Israel"
    },
  // {
  //   "id": 11,
  //   "name": "Ethan Cohen",
  //   "profession": "AI Researcher",
  //   "hobbies": "Reading, Playing Guitar, AI experiments",
  //   "codeLanguages": "Python, TensorFlow",
  //   "lifePhilosophy": "Explore the unknown.",
  //   "email": "ethan.cohen@example.com",
  //   "phone": "+5554443333",
  //   "city": "Rehovot",
  //   "country": "Israel"
  // },
  // {
  //   "id": 12,
  //   "name": "Lily Levi",
  //   "profession": "UI/UX Designer",
  //   "hobbies": "Photography, Traveling, Sketching",
  //   "codeLanguages": "None",
  //   "lifePhilosophy": "Design is intelligence made visible.",
  //   "email": "lily.levi@example.com",
  //   "phone": "+9998887777",
  //   "city": "Raanana",
  //   "country": "Israel"
  // },
  // {
  //   "id": 13,
  //   "name": "Jordan Amar",
  //   "profession": "Software Architect",
  //   "hobbies": "Gaming, Playing Piano, Cooking",
  //   "codeLanguages": "Java, Python, C#",
  //   "lifePhilosophy": "Simplicity is the ultimate sophistication.",
  //   "email": "jordan.amar@example.com",
  //   "phone": "+3332221111",
  //   "city": "Hadera",
  //   "country": "Israel"
  // },
  // {
  //   "id": 14,
  //   "name": "Zoe Ariel",
  //   "profession": "Full Stack Developer",
  //   "hobbies": "Reading, Biking, Coding",
  //   "codeLanguages": "JavaScript, Python, Java",
  //   "lifePhilosophy": "Stay hungry, stay foolish.",
  //   "email": "zoe.ariel@example.com",
  //   "phone": "+7776665555",
  //   "city": "Nahariya",
  //   "country": "Israel"
  // },
  // {
  //   "id": 15,
  //   "name": "Aiden Gold",
  //   "profession": "Cybersecurity Analyst",
  //   "hobbies": "Soccer, Traveling, Ethical Hacking",
  //   "codeLanguages": "Python, C",
  //   "lifePhilosophy": "Security is everyone's responsibility.",
  //   "email": "aiden.gold@example.com",
  //   "phone": "+1112223333",
  //   "city": "Kfar Saba",
  //   "country": "Israel"
  // },
  // {
  //   "id": 16,
  //   "name": "Sophia Levi",
  //   "profession": "Data Analyst",
  //   "hobbies": "Reading, Painting, Yoga",
  //   "codeLanguages": "SQL, Python",
  //   "lifePhilosophy": "Every problem has a solution.",
  //   "email": "sophia.levi@example.com",
  //   "phone": "+4445556666",
  //   "city": "Beit Shemesh",
  //   "country": "Israel"
  // },
  // {
  //   "id": 17,
  //   "name": "Noah Yosef",
  //   "profession": "Backend Developer",
  //   "hobbies": "Hiking, Cooking, Playing Piano",
  //   "codeLanguages": "Java, Node.js",
  //   "lifePhilosophy": "Persistence conquers all.",
  //   "email": "noah.yosef@example.com",
  //   "phone": "+5554443333",
  //   "city": "Modi'in",
  //   "country": "Israel"
  // },
  // {
  //   "id": 18,
  //   "name": "Emma Cohen",
  //   "profession": "UX Researcher",
  //   "hobbies": "Traveling, Photography, Dancing",
  //   "codeLanguages": "None",
  //   "lifePhilosophy": "Listen and learn.",
  //   "email": "emma.cohen@example.com",
  //   "phone": "+9998887777",
  //   "city": "Ashkelon",
  //   "country": "Israel"
  // },
  // {
  //   "id": 19,
  //   "name": "Isaac Ben-David",
  //   "profession": "Frontend Developer",
  //   "hobbies": "Painting, Biking, Coding",
  //   "codeLanguages": "JavaScript, HTML, CSS",
  //   "lifePhilosophy": "Be curious, not judgmental.",
  //   "email": "isaac.ben-david@example.com",
  //   "phone": "+3332221111",
  //   "city": "Lod",
  //   "country": "Israel"
  // },
  // {
  //   "id": 20,
  //   "name": "Mia Cohen",
  //   "profession": "Machine Learning Engineer",
  //   "hobbies": "Reading, Chess, Coding",
  //   "codeLanguages": "Python, TensorFlow",
  //   "lifePhilosophy": "Challenge accepted.",
  //   "email": "mia.cohen@example.com",
  //   "phone": "+7776665555",
  //   "city": "Eilat",
  //   "country": "Israel"
  // },

  // {
  //   id: 1,
  //   name: "Seldon",
  //   ingredients: "phisics",
  //   location: "Haifa",
  //   price: "50 🤑",
  //   photoName: "images/Sheldon.jpg",
  //   soldOut: false,
  //   contact: "0546457645",
  // },
  // {
  //   id: 2,
  //   name: "Leonard",
  //   ingredients: "Phisics",
  //   location: "Tel Aviv",
  //   price: "10 🤑",
  //   photoName: "images/leonard.jpg",
  //   soldOut: false,
  //   contact: "0575748745",
  // },
  // {
  //   id: 3,
  //   name: "Penny",
  //   ingredients: "theatre",
  //   location: "Jerusalem",
  //   price: "41 🤑",
  //   photoName: "images/penny.jpg",
  //   soldOut: false,
  // },
  // {
  //   id: 4,
  //   name: "Amy",
  //   ingredients: "Biology",
  //   location: "Netanya",
  //   price: "90 🤑",
  //   photoName: "images/amy.jpg",
  //   soldOut: false,
  //   contact: "1111111111",
  // },
  // {
  //   id: 5,
  //   name: "Howard",
  //   ingredients: "computer science",
  //   location: "Haifa",
  //   price: "14 🤑",
  //   photoName: "images/howard.jpg",
  //   soldOut: true,
  //   contact: "68765975543",
  // },
  // {
  //   id: 6,
  //   name: "Rajesh",
  //   ingredients: "Math",
  //   location: "Tel Aviv",
  //   price: "18 🤑",
  //   photoName: "images/rajesh.jpg",
  //   soldOut: false,
  //   contact: "687659567653",
  // },
];

module.exports = teachers;